In [2]:
# Identifiers and Keywords (H1)
# Identifiers: variable, function, class names
# Keywords: reserved words like `def`, `class`, `if`, `else`, etc.


name = "Ashish"  # 'name' is an identifier
age = 21         # 'age' is also an identifier


def greet():     # 'def' is a keyword, 'greet' is an identifier
    print("Hello", name)


greet()


Hello Ashish


In [6]:
#Indentation
# Python uses indentation (spaces or tabs) to define code blocks


x = 10


if x > 5:
    print("x is greater than 5")   # indented block inside if
    print("This line is also part of the if block")
print("This line is outside the if block")  # no indentation


x is greater than 5
This line is also part of the if block
This line is outside the if block


In [8]:
#Comments

"""
This is a 
multi-line comment or docstring.
Used to describe what your code does.
"""

# Below is a sample program
a = 5  # assigning value 5 to variable a
b = 3
sum = a + b  # adding a and b
print("Sum is:", sum)


Sum is: 8


In [3]:
#Operators
a = 10
b = 3

# Arithmetic Operators
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Modulus:", a % b)
print("Power:", a ** b)

# Comparison Operators
print("Is a equal to b?", a == b)
print("Is a not equal to b?", a != b)
print("Is a greater than b?", a > b)

Addition: 13
Subtraction: 7
Multiplication: 30
Division: 3.3333333333333335
Modulus: 1
Power: 1000
Is a equal to b? False
Is a not equal to b? True
Is a greater than b? True


In [11]:
#Membership Operator
my_list = [1, 2, 3, 4, 5]

print(3 in my_list)    # True
print(7 in my_list)    # False
print(10 not in my_list)  # True

my_string = "hello"
print('h' in my_string)  # True
print('z' in my_string)  # False


True
False
True
True
False


In [13]:
#2. Write programs to understand the use of Python String, Tuple, List, Set, Dictionary, File input/output.

In [2]:
#String
# String operations
text = "Hello, Python!"

print(text.upper())         # Convert to uppercase
print(text.lower())         # Convert to lowercase
print(text[0:5])            # Slicing
print("Python" in text)     # Membership check
print(text.replace("Python", "World"))

HELLO, PYTHON!
hello, python!
Hello
True
Hello, World!


In [3]:
#Tuple
# Tuples are immutable collections
my_tuple = (10, 20, 30, 40)

print(my_tuple[1])          # Accessing element
print(len(my_tuple))        # Length of tuple
print(20 in my_tuple)       # Membership check

# my_tuple[0] = 100  ❌ Error: Tuples are immutable

20
4
True


In [6]:
#List
# Lists are mutable
my_list = [1, 2, 3]

my_list.append(4)           # Add element
my_list.remove(2)           # Remove element
my_list[0] = 100            # Modify element

print(my_list)
print(len(my_list))

[100, 3, 4]
3


In [5]:
#Set
# Sets are unordered and store unique values
my_set = {1, 2, 3, 3, 4}

my_set.add(5)               # Add item
my_set.discard(2)           # Remove item if present

print(my_set)
print(3 in my_set)          # Membership

{1, 3, 4, 5}
True


In [4]:
#Dictionary
# Dictionary stores key-value pairs
student = {
    "name": "Ashish",
    "age": 21,
    "branch": "CSE"
}

print(student["name"])      # Access by key
student["age"] = 22         # Modify value
student["city"] = "Raipur"  # Add new key-value

for key, value in student.items():
    print(f"{key}: {value}")

Ashish
name: Ashish
age: 22
branch: CSE
city: Raipur


In [18]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [19]:
"""Write programs to understand the use of Numpy’s Ndarray, Basic Operations, Indexing, Slicing, and Iterating,
Conditions and Boolean Arrays."""

#Creating an ndarray
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr)

matrix = np.array([[1, 2], [3, 4]])
print("2D Array:\n", matrix)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2]
 [3 4]]


In [20]:
#Basic Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", b / a)
print("Square:", a ** 2)
print("Sum of all elements:", np.sum(a))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Square: [1 4 9]
Sum of all elements: 6


In [21]:
#Indexing, Slicing, and Iterating
arr = np.array([10, 20, 30, 40, 50])

print("Element at index 2:", arr[2])
print("Sliced Array:", arr[1:4])

print("Iterating over array:")
for x in arr:
    print(x)


Element at index 2: 30
Sliced Array: [20 30 40]
Iterating over array:
10
20
30
40
50


In [22]:
#Multidimensional Indexing and Slicing
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Element at [1][2]:", matrix[1][2])
print("Row 2:", matrix[1])
print("Column 1:", matrix[:, 0])
print("Sub-matrix:\n", matrix[0:2, 1:3])

Element at [1][2]: 6
Row 2: [4 5 6]
Column 1: [1 4 7]
Sub-matrix:
 [[2 3]
 [5 6]]


In [23]:
#Conditions and Boolean Arrays
arr = np.array([5, 10, 15, 20, 25])

bool_arr = arr > 15
print("Condition arr > 15:", bool_arr)

filtered = arr[arr > 15]
print("Filtered values (arr > 15):", filtered)

# Multiple conditions
print("Values between 10 and 25:", arr[(arr > 10) & (arr < 25)])

Condition arr > 15: [False False False  True  True]
Filtered values (arr > 15): [20 25]
Values between 10 and 25: [15 20]


In [7]:
#Write programs to understand the use of Numpy’s Shape Manipulation, Array Manipulation, Vectorization.

#1. Shape Manipulation
import numpy as np

# Original array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original shape:", arr.shape)

# Reshape
reshaped = arr.reshape(3, 2)
print("Reshaped (3x2):\n", reshaped)

# Flatten (1D)
flat = arr.flatten()
print("Flattened array:", flat)

# Transpose
transposed = arr.T
print("Transposed:\n", transposed)


Original shape: (2, 3)
Reshaped (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Flattened array: [1 2 3 4 5 6]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


In [8]:

    #2. Array Manipulation
    import numpy as np
    
    a = np.array([[1, 2], [3, 4]])
    b = np.array([[5, 6]])
    
    # Stack vertically (row-wise)
    vstacked = np.vstack((a, b))
    print("Vertically stacked:\n", vstacked)
    
    # Stack horizontally (column-wise)
    c = np.array([[5], [6]])
    hstacked = np.hstack((a, c))
    print("Horizontally stacked:\n", hstacked)
    
    # Split array
    arr = np.array([1, 2, 3, 4, 5, 6])
    split = np.split(arr, 3)
    print("Split array into 3 parts:", split)

Vertically stacked:
 [[1 2]
 [3 4]
 [5 6]]
Horizontally stacked:
 [[1 2 5]
 [3 4 6]]
Split array into 3 parts: [array([1, 2]), array([3, 4]), array([5, 6])]


In [9]:
#3. Vectorization
import numpy as np

# Without vectorization (using loop)
data = [1, 2, 3, 4]
squared = []
for x in data:
    squared.append(x**2)
print("Using loop:", squared)

# With NumPy vectorization
arr = np.array([1, 2, 3, 4])
squared_np = arr ** 2
print("Using NumPy vectorization:", squared_np)

# Vectorized operations with functions
def f(x):
    return x**2 + 3*x + 2

result = f(arr)  # Automatically applied element-wise
print("Function vectorized result:", result)

Using loop: [1, 4, 9, 16]
Using NumPy vectorization: [ 1  4  9 16]
Function vectorized result: [ 6 12 20 30]


In [26]:
'''Write programs to understand the use of Numpy’s Structured Arrays, Reading and Writing Array Data on
Files'''

#1. Structured Arrays in NumPy
#Structured arrays allow different data types for each column (like a database table).

import numpy as np

# Define structured data type
student_dtype = np.dtype([
    ('name', 'U10'),   # Unicode string (max 10 chars)
    ('age', 'i4'),     # 32-bit integer
    ('marks', 'f4')    # 32-bit float
])

# Create structured array
students = np.array([
    ('Alice', 20, 85.5),
    ('Bob', 22, 90.0),
    ('Charlie', 21, 78.2)
], dtype=student_dtype)

# Access structured data
print("All student names:", students['name'])
print("Age of second student:", students[1]['age'])
print("All student records:\n", students)


All student names: ['Alice' 'Bob' 'Charlie']
Age of second student: 22
All student records:
 [('Alice', 20, 85.5) ('Bob', 22, 90. ) ('Charlie', 21, 78.2)]


In [27]:
#22. Writing Array Data to File (Text File)
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

# Save as plain text
np.savetxt("my_array.txt", arr, fmt='%d')
print("Array saved to my_array.txt")

Array saved to my_array.txt


In [28]:
#3. Reading Array Data from File (Text File)
import numpy as np

# Read from text file
loaded_arr = np.loadtxt("my_array.txt", dtype=int)
print("Loaded array:\n", loaded_arr)

Loaded array:
 [[10 20 30]
 [40 50 60]]


In [10]:
#4. Save & Load as Binary (npy format)
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Save binary file
np.save('my_binary_array.npy', arr)

# Load binary file
loaded = np.load('my_binary_array.npy')
print("Loaded from .npy file:\n", loaded)

Loaded from .npy file:
 [[1 2 3]
 [4 5 6]]
